In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from sklearn.metrics import r2_score

import Functions

In [85]:
df_stats = pd.read_csv('/home/frank/Desktop/f.chiapperino_local/VALENCIA/SCUOLA/App/Documents/csv/TimeSeries_Coherencia.csv', index_col='Code')
df_stats['Date'] = pd.to_datetime(df_stats['Date'])
display(df_stats)

           Date_Band      mean       std       Date Band      Name      Type
Code
1841224  20170104_VH  0.846021  0.060364 2017-01-04   VH    DB_A_C  Potatoes
1841224  20170104_VV  0.912519  0.032522 2017-01-04   VV    DB_A_C  Potatoes
1841224  20170110_VH  0.470780  0.095106 2017-01-10   VH    DB_A_C  Potatoes
1841224  20170110_VV  0.660484  0.081345 2017-01-10   VV    DB_A_C  Potatoes
1841224  20170116_VH  0.311812  0.113724 2017-01-16   VH    DB_A_C  Potatoes
...              ...       ...       ...        ...  ...       ...       ...
1841225  20171212_VV  0.191203  0.106592 2017-12-12   VV  DB_SB1_C     Beets
1841225  20171218_VH  0.916552  0.026221 2017-12-18   VH  DB_SB1_C     Beets
1841225  20171218_VV  0.957047  0.016386 2017-12-18   VV  DB_SB1_C     Beets
1841225  20171224_VH  0.895575  0.024988 2017-12-24   VH  DB_SB1_C     Beets
1841225  20171224_VV  0.939907  0.019482 2017-12-24   VV  DB_SB1_C     Beets

[3024 rows x 7 columns]

In [86]:
df_stats.drop(df_stats[df_stats['mean'] == 0].index,inplace=True)
display(pd.unique(df_stats.index))

Index([1841224, 1936134, 2088262, 1576641, 1697689, 1896343, 2278835, 1601502,
       1936133, 1824038, 1545384, 1553694, 2081268, 2081267, 2081887, 1767881,
       1698168, 1841223, 1936135, 2041694, 1697690, 1631664, 1841225],
      dtype='int64', name='Code')

In [92]:
df_height = pd.read_csv(r'/home/frank/Desktop/f.chiapperino_local/VALENCIA/SCUOLA/App/Documents/csv/Averaged_crop_height.csv', header=0)
df_height=df_height.set_index(df_height['Code'])
df_height = df_height.drop(columns=['Code'])
display(df_height)

,2017-05-18 00:00:00,2017-05-23 00:00:00,2017-05-30 00:00:00,2017-06-08 00:00:00,2017-06-15 00:00:00,2017-06-21 00:00:00,2017-06-27 00:00:00,2017-07-03 00:00:00,2017-07-06 00:00:00,2017-07-13 00:00:00,2017-07-17 00:00:00,2017-07-27 00:00:00,2017-08-02 00:00:00,2017-08-11 00:00:00,2017-08-17 00:00:00,2017-08-23 00:00:00,2017-09-01 00:00:00,2017-09-07 00:00:00,2017-09-15 00:00:00
Code,,,,,,,,,,,,,,,,,,,
1545384.0,NaN,NaN,NaN,NaN,NaN,59.5,67.5,84.0,NaN,83.50,85.00,87.5,71.0,75.00,60.00,52.50,NaN,53.50,25.0
1553694.0,NaN,NaN,NaN,NaN,NaN,53.0,56.5,57.5,NaN,75.50,75.00,71.5,73.5,66.00,82.50,77.50,NaN,79.00,NaN
1576641.0,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,77.0,NaN,90.00,NaN,10.0,NaN,NaN,NaN,15.0,NaN,NaN
1601502.0,NaN,NaN,NaN,NaN,NaN,42.5,51.5,58.0,NaN,NaN,59.00,62.0,65.0,64.00,70.00,78.50,NaN,77.50,NaN
1631664.0,21.0,23.0,38.0,NaN,9.0,14.0,20.0,20.5,NaN,31.00,37.75,NaN,24.0,28.25,17.00,23.00,NaN,23.75,20.0
1697689.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.00,15.00,NaN,22.0,NaN,20.00,NaN,32.5,NaN,NaN
1697690.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.00,18.00,NaN,30.0,NaN,25.00,NaN,35.0,NaN,NaN
1697691.0,NaN,NaN,NaN,NaN,NaN,NaN,58.5,NaN,NaN,40.00,45.00,NaN,45.0,NaN,55.00,NaN,30.0,NaN,NaN
1698168.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,240.00,250.00,NaN,270.0,NaN,NaN,NaN,NaN,NaN,NaN
1767881.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.0,NaN,NaN,NaN,12.5,NaN,NaN
1824038.0,40.5,8.0,20.0,27.0,17.0,21.0,31.0,49.5,NaN,77.50,75.00,NaN,21.5,35.00,NaN,32.50,NaN,27.50,30.0
1841223.0,NaN,70.0,NaN,81.5,NaN,78.5,83.0,82.0,NaN,84.00,82.50,17.5,NaN,15.00,8.75,11.25,NaN,14.50,20.0
1841225.0,NaN,NaN,NaN,NaN,NaN,56.0,67.0,71.5,NaN,70.75,81.00,81.0,76.0,76.50,75.00,77.50,NaN,85.00,NaN
1889479.0,NaN,NaN,NaN,NaN,NaN,NaN,61.5,NaN,NaN,60.00,65.00,NaN,50.0,NaN,45.00,NaN,50.0,NaN,NaN
1889482.0,NaN,NaN,NaN,NaN,NaN,NaN,58.0,NaN,NaN,55.00,55.00,NaN,45.0,NaN,25.00,NaN,20.0,NaN,NaN
1896343.0,NaN,NaN,NaN,37.0,55.0,86.0,121.0,158.5,NaN,225.00,242.50,290.0,300.0,300.00,295.00,300.00,NaN,295.00,NaN
1936133.0,NaN,NaN,NaN,NaN,NaN,42.5,51.0,NaN,NaN,77.50,100.00,NaN,99.0,115.00,110.00,82.50,NaN,86.50,NaN
1936134.0,NaN,NaN,NaN,NaN,NaN,41.5,46.5,51.5,NaN,62.75,66.50,68.0,72.0,68.00,75.00,68.50,NaN,67.00,54.0
1936135.0,49.0,57.5,NaN,66.0,71.0,62.5,69.5,70.0,NaN,68.50,67.50,64.0,63.5,NaN,7.50,8.50,NaN,15.25,10.0
2041694.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,85.00,NaN,60.0,NaN,60.00,NaN,47.5,NaN,NaN
2081267.0,73.0,68.0,80.0,90.0,NaN,91.5,93.5,88.5,NaN,NaN,88.50,85.5,83.5,22.50,17.50,15.00,NaN,35.50,30.0
2081268.0,NaN,NaN,NaN,NaN,NaN,47.5,53.5,63.0,NaN,NaN,76.00,71.5,71.0,72.50,81.00,68.50,NaN,72.00,45.0
2081887.0,NaN,NaN,NaN,NaN,70.0,102.5,NaN,NaN,NaN,240.00,260.00,290.0,287.5,292.50,292.50,292.50,NaN,290.00,300.0
2088262.0,NaN,NaN,NaN,45.0,56.0,97.5,155.0,181.5,NaN,260.00,273.75,315.0,302.5,315.00,305.00,307.50,NaN,297.50,290.0
2278835.0,NaN,NaN,NaN,NaN,NaN,95.5,130.0,173.5,NaN,235.00,270.00,293.5,300.0,290.00,297.50,292.50,NaN,300.00,295.0
2294423.0,NaN,NaN,NaN,NaN,NaN,NaN,54.5,NaN,NaN,50.00,45.00,NaN,37.5,NaN,45.00,NaN,27.5,NaN,NaN

In [93]:
df_rain = pd.read_csv('/home/frank/Desktop/f.chiapperino_local/VALENCIA/SCUOLA/App/Documents/csv/rainfall_week.csv', header=0)
display(df_rain)

          date  prec_mm
0   2017-01-04     23.0
1   2017-01-10     58.8
2   2017-01-16      0.0
3   2017-01-22      7.8
4   2017-01-28     20.1
..         ...      ...
58  2017-12-18      5.7
59  2017-12-24     37.8
60  2017-12-30    112.0
61  2018-01-05      6.3
62  2018-01-11      0.9

[63 rows x 2 columns]

In [108]:
# Filtra i dati per la parcella 1553694
df_growth_beets = df_height.loc[1553694].dropna()

# 1. Creazione di un indice giornaliero per non perdere i "denti"
daily_index = pd.date_range(start=df_growth_beets.index.min(), 
                             end=df_growth_beets.index.max(), freq='D')
display(type(daily_index))

pandas.DatetimeIndex

In [107]:
# 2. Interpolazione PCHIP (preserva meglio la forma a dente di sega rispetto alla lineare)
from scipy.interpolate import pchip_interpolate
growth_interp = df_growth_beets.reindex(daily_index).interpolate(method='pchip')
print(growth_interp.iloc[5:10])

2017-06-26   NaN
2017-06-27   NaN
2017-06-28   NaN
2017-06-29   NaN
2017-06-30   NaN
Freq: D, Name: 1553694.0, dtype: float64

regressione

In [ ]:
from sklearn.linear_model import LassoCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score

X =